---
title: "breast cancer wisconsin (Dx)"
author: "Rich Chien"
date: "November 21, 2016"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Get input data


```{r input, message=F, warning=F}
set.seed(7)
library(dplyr)
library(ggplot2)
library(caret)

df <- read.csv("C:/Users/RC3258/Documents/GitRepo/ds_wisconsin-bc/data.csv")

# delete id and X columns
df <- df %>%
  select(-id, -X)
```


## Setup train and test sets

```{r traintest}

# take random 70% to train
index <- sample(1:nrow(df),size = 0.7*nrow(df)) 
train <- df[index, ] 
test <- df[-index, ] 


```

## Setup models


```{r models, warning=F, message=F}

# (optional multiple core setup)
# library(doParallel)
# registerDoParallel(cores=4)
# getDoParWorkers()


# prepare training ctrl
ctrl <- trainControl(method="repeatedcv", number=10, repeats=3)


# train linear model
m.glm <- train(diagnosis~., data=train, method="glm", trControl=ctrl)

# train LVQ model
m.lvq <- train(diagnosis~., data=train, method="lvq", trControl=ctrl)

# train GBM model
m.gbm <- train(diagnosis~., data=train, method="gbm", trControl=ctrl, verbose=F)

# train SVM model
m.svm <- train(diagnosis~., data=train, method="svmRadial", trControl=ctrl)

# train rf model
m.rf <- train(diagnosis~., data=train, method="rf", trControl=ctrl)

# collect resamples
results <- resamples(list(glm=m.glm, lvq=m.lvq, gbm=m.gbm, svm=m.svm, rf=m.rf))

# summarize 
summary(results)
bwplot(results)
dotplot(results)
```


```{r gbm, eval=F, warning=F, message=F}

# examine gbm model
ctrlgbm <- trainControl(method="repeatedcv", number=10, 
                        repeats=3, summaryFunction=twoClassSummary, classProbs=T)
# train GBM model
m2.gbm <- train(diagnosis~., data=train, method="gbm",  metric="ROC", 
               trControl=ctrlgbm, verbose=F)

plot(m2.gbm)
m2.gbm$bestTune


# predict test set using model
pred2.gbm <- predict(m2.gbm, test)

# confusion matrix
confusionMatrix(pred2.gbm, test$diagnosis)

# ROC curve
pred2.gbm.prob <- predict(m2.gbm, test, type="prob")

auc <- roc(ifelse(test[,1]=="M",1,0), pred2.gbm.prob[[2]])
print(auc$auc)

# accuracy calc
res <- table(pred.svm, test$diagnosis)
accuracy <- round(100 * sum(diag(res))/sum(res), 2)

# save model
# saveRDS(m.svm, "./m.svm.rds")
 
# load model
# m.svm <- readRDS("./m.svm.rds")

```



